name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose*.yml'
      - 'monitoring/**'
      - '.env.production.example'
      - 'scripts/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH }}/deploiementproject

jobs:
  validate:
    name: Validate Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate docker-compose files
        run: |
          docker-compose -f docker-compose.yml config -q
          docker-compose -f docker-compose.yml -f docker-compose.monitoring.yml config -q
          docker-compose -f docker-compose.yml -f docker-compose.apps.yml config -q
          echo "All docker-compose files are valid"

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: validate
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to VPS
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key" \
            --exclude '.git' \
            --exclude '.forgejo' \
            --exclude 'templates' \
            --exclude 'README*.md' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ env.DEPLOY_PATH }}/

      - name: Deploy infrastructure
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'DEPLOY_SCRIPT'
            set -e
            cd ${{ env.DEPLOY_PATH }}

            echo "=== Pulling latest images ==="
            docker-compose -f docker-compose.yml -f docker-compose.monitoring.yml pull

            echo "=== Starting infrastructure services ==="
            docker-compose -f docker-compose.yml -f docker-compose.monitoring.yml up -d

            echo "=== Cleaning up old images ==="
            docker image prune -f

            echo "=== Deployment completed ==="
          DEPLOY_SCRIPT

      - name: Health check
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'HEALTH_SCRIPT'
            set -e
            cd ${{ env.DEPLOY_PATH }}

            echo "=== Waiting for services to be healthy ==="
            sleep 10

            # Check PostgreSQL
            if docker exec postgres-db pg_isready -U postgres > /dev/null 2>&1; then
              echo "PostgreSQL: OK"
            else
              echo "PostgreSQL: FAILED"
              exit 1
            fi

            # Check Prometheus
            if curl -sf http://localhost:9190/-/healthy > /dev/null 2>&1; then
              echo "Prometheus: OK"
            else
              echo "Prometheus: FAILED (may need more time)"
            fi

            # Check Grafana
            if curl -sf http://localhost:3000/api/health > /dev/null 2>&1; then
              echo "Grafana: OK"
            else
              echo "Grafana: FAILED (may need more time)"
            fi

            echo "=== Health check completed ==="
          HEALTH_SCRIPT

      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/deploy_key

  notify:
    name: Notify deployment status
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Deployment status
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "Infrastructure deployment successful!"
          else
            echo "Infrastructure deployment failed!"
            exit 1
          fi
